# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  # print_hello:
  #   docker:
  #     - image: circleci/node:13.8.0
  #   steps:
  #     - run:
  #         name: "Hello Job"
  #         command: "echo hello"

  # print_world:
  #   docker:
  #     - image: circleci/node:13.8.0
  #   steps:
  #     - run:
  #         name: "world Job"
  #         command: "echo world"
  
  # global_var:
  #   docker:
  #     - image: circleci/node:13.8.0
  #   steps:
  #     - run:
  #         name: "global var Job"
  #         command: "echo My pipeline id is << pipeline.id >> and my git branch is << pipeline.git.branch >>"
  #     - run:
  #         name: "Env Variables Job"
  #         command: "echo $MY_ENV_NAME"

  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: "save hello world to workspace"
          command: "echo 'Hello World!!' > output.txt"
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - output.txt

  print_output_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: "Restor hello world from output.txt"
          command: "cat output.txt"
      - attach_workspace:
          at: /tmp/workspace



# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  default-workflow:
    jobs:
      # - print_hello
      # - print_world:
      #     requires: 
      #       - print_hello
      # - global_var
      - save_hello_world_output
      - print_output_file
